"""Champion database (aliases, localized names) and minimap icons (+ downloaded skin icons).

* The roster comes from ``assets/icons/champions/index.json`` (generated by
  ``tools/fetch_assets.py``): ``{"patch": ..., "champions": [{"alias", "key", "name_en",
  "name_fr", "tags", "icon", "icon_source"}]}``.
* :meth:`ChampionDB.load_icon` returns the round portrait drawn inside the minimap ring
  (RGBA uint8): the downloaded skin icon ``<cache>/<Alias>_<skin>.png`` when present, else
  the bundled base icon.
* :meth:`ChampionDB.prefetch_skin_icons` downloads the skin icons of the current players from
  CommunityDragon in a background daemon thread (explicit User-Agent, 5 s timeout, 404s
  remembered, atomic writes, silent failures). It is the only network access of this module.
  It also downloads the BASE icon (``<cache>/<Alias>_0.png``) of a champion released after the
  app build (no bundled icon), so new champions get a roster portrait without a release.
* The process-wide database (:func:`get_default_db`) also lists the champions of the runtime
  Data Dragon refresh (:mod:`treeaicoach.game_data`) missing from the bundled index (new
  champions, French names), and reloads when that data is updated.
"""

from __future__ import annotations

import collections
import json
import logging
import os
import re
import tempfile
import threading
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, Iterable

import cv2
import numpy as np

if TYPE_CHECKING:  # pragma: no cover
    from treeaicoach.live_client import PlayerInfo

log = logging.getLogger(__name__)

try:
    from treeaicoach import __version__ as _APP_VERSION
except Exception:  # pragma: no cover - defensive
    _APP_VERSION = "1.0.0"

RAW_CHAMPION_PREFIX = "game_character_displayname_"
RAW_SKIN_PREFIX = "game_character_skin_displayname_"

#: CommunityDragon characters directory (monkeypatchable; ``ChampionDB.base_url`` overrides it).
CDRAGON_CHARACTERS_URL = "https://raw.communitydragon.org/latest/game/assets/characters"
SKIN_ICON_URL_TEMPLATE = "{base}/{alias}/hud/{alias}_circle_{skin}.png"
#: Base (skin 0) minimap circle of a champion: ``<alias>_circle.png`` (some use ``_circle_0.png``).
BASE_ICON_URL_TEMPLATE = "{base}/{alias}/hud/{alias}_circle.png"
USER_AGENT = f"TreeAICoach/{_APP_VERSION} (screen-capture LoL coach; skin icon cache)"
DOWNLOAD_TIMEOUT_S = 5.0
MAX_DOWNLOAD_BYTES = 4 * 1024 * 1024
#: Failed (non-404) downloads are retried after this delay; network errors pause all downloads.
RETRY_AFTER_S = 300.0
#: Downloaded icons are stored at the size of the bundled ones.
CACHED_ICON_SIZE = 64
ICON_LRU_SIZE = 96
MIN_ICON_SIDE = 8
MAX_ICON_SIDE = 2048
_LOOPBACK = {"127.0.0.1", "localhost", "::1"}


@dataclass(frozen=True)
class ChampionEntry:
    """One champion of the bundled index."""

    alias: str          # Data Dragon id, e.g. "MonkeyKing" (== Live Client rawChampionName suffix)
    key: int            # numeric champion id (62)
    name_en: str        # "Wukong"
    name_fr: str        # "Wukong"
    icon_file: str      # file name in assets/icons/champions ("MonkeyKing.png")
    tags: tuple[str, ...] = ()


def alias_from_raw(raw: str) -> str:
    """``"game_character_displayname_MonkeyKing"`` -> ``"MonkeyKing"``; clean aliases unchanged.

    Also accepts raw skin names (``"game_character_skin_displayname_Annie_1"`` -> ``"Annie"``).
    ``None`` / non-strings give ``""``.
    """
    if raw is None:
        return ""
    s = str(raw).strip()
    low = s.lower()
    if low.startswith(RAW_CHAMPION_PREFIX):
        return s[len(RAW_CHAMPION_PREFIX):].strip()
    if low.startswith(RAW_SKIN_PREFIX):
        rest = s[len(RAW_SKIN_PREFIX):].strip()
        m = re.fullmatch(r"(.+?)_(\d+)", rest)
        return m.group(1) if m else rest
    return s


def normalize_name(name: Any) -> str:
    """Lookup key: accents removed, case-folded, only letters and digits ("K'Santé" -> "ksante")."""
    if name is None:
        return ""
    s = unicodedata.normalize("NFKD", str(name))
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    return "".join(ch for ch in s.casefold() if ch.isalnum())


def _safe_int(x: Any, default: int = 0) -> int:
    try:
        return int(x)
    except (TypeError, ValueError, OverflowError):
        try:
            return int(float(x))
        except (TypeError, ValueError, OverflowError):
            return default


def _to_rgba(img: np.ndarray | None) -> np.ndarray | None:
    """Convert a cv2-decoded image (gray / BGR / BGRA, 8 or 16 bit) to RGBA uint8."""
    if img is None or not isinstance(img, np.ndarray) or img.size == 0:
        return None
    if img.dtype == np.uint16:
        img = (img >> 8).astype(np.uint8)
    elif img.dtype != np.uint8:
        img = np.clip(img, 0, 255).astype(np.uint8)
    if img.ndim == 2:
        return cv2.cvtColor(img, cv2.COLOR_GRAY2RGBA)
    if img.ndim != 3:
        return None
    ch = img.shape[2]
    if ch == 4:
        return cv2.cvtColor(img, cv2.COLOR_BGRA2RGBA)
    if ch == 3:
        return cv2.cvtColor(img, cv2.COLOR_BGR2RGBA)
    if ch == 1:
        return cv2.cvtColor(img[:, :, 0], cv2.COLOR_GRAY2RGBA)
    return None


def _valid_icon(img: np.ndarray | None) -> bool:
    if img is None:
        return False
    h, w = img.shape[:2]
    return MIN_ICON_SIDE <= h <= MAX_ICON_SIDE and MIN_ICON_SIDE <= w <= MAX_ICON_SIDE


def decode_rgba(data: bytes) -> np.ndarray | None:
    """Decode encoded image bytes (PNG...) to RGBA uint8; ``None`` if invalid."""
    try:
        if not data:
            return None
        img = cv2.imdecode(np.frombuffer(data, dtype=np.uint8), cv2.IMREAD_UNCHANGED)
        rgba = _to_rgba(img)
        return rgba if _valid_icon(rgba) else None
    except Exception:  # cv2.error on corrupt data
        log.debug("decode_rgba: undecodable image data", exc_info=True)
        return None


def read_rgba(path: Path | str) -> np.ndarray | None:
    """Read an image file as RGBA uint8 (works with non-ASCII Windows paths); ``None`` on error."""
    try:
        p = Path(path)
        if not p.is_file():
            return None
        return decode_rgba(np.fromfile(str(p), dtype=np.uint8).tobytes())
    except Exception:
        log.debug("read_rgba: cannot read %s", path, exc_info=True)
        return None


def _default_assets_dir() -> Path:
    try:
        from treeaicoach import paths  # written in parallel; optional at import time

        return Path(paths.asset_path())
    except Exception:
        return Path(__file__).resolve().parent / "assets"


def _default_cache_dir() -> Path:
    try:
        from treeaicoach import paths

        return Path(paths.cache_dir())
    except Exception:
        log.debug("paths.cache_dir() unavailable, using ~/.treeaicoach/cache", exc_info=True)
        return Path.home() / ".treeaicoach" / "cache"


def _no_proxy_opener() -> urllib.request.OpenerDirector:
    return urllib.request.build_opener(urllib.request.ProxyHandler({}))


class ChampionDB:
    """Champion roster + icon loader. Thread-safe."""

    def __init__(self, assets_dir: Path | None = None, cache_dir: Path | None = None,
                 runtime_data: bool | None = None):
        self._lock = threading.RLock()
        #: merge the champions of the runtime Data Dragon refresh (default: only on the bundled assets)
        self._runtime_data = (assets_dir is None) if runtime_data is None else bool(runtime_data)
        self._entries: list[ChampionEntry] = []
        self._by_norm: dict[str, ChampionEntry] = {}
        self._by_key: dict[int, ChampionEntry] = {}
        self.patch: str = ""
        self._icons_dir = self._resolve_icons_dir(assets_dir)
        self._cache_dir: Path | None = Path(cache_dir) if cache_dir is not None else None
        self._cache_dir_resolved = cache_dir is not None
        #: Override of :data:`CDRAGON_CHARACTERS_URL` for this instance (tests).
        self.base_url: str | None = None
        self._lru: collections.OrderedDict[tuple[str, int], np.ndarray] = collections.OrderedDict()
        self._warned_missing_icon: set[str] = set()
        # download state (guarded by self._lock)
        self._missing: set[tuple[str, int]] = set()        # 404 / invalid content: never retried
        self._failed_at: dict[tuple[str, int], float] = {}  # transient failures
        self._downloaded: set[tuple[str, int]] = set()
        self._queue: collections.deque[tuple[str, int]] = collections.deque()
        self._queued: set[tuple[str, int]] = set()
        self._worker: threading.Thread | None = None
        self._offline_until = 0.0
        self._stop = threading.Event()
        self._load_index()

    # ------------------------------------------------------------------ index
    @staticmethod
    def _resolve_icons_dir(assets_dir: Path | None) -> Path:
        base = Path(assets_dir) if assets_dir is not None else _default_assets_dir()
        try:
            if (base / "index.json").is_file():   # the champions icon folder itself was given
                return base
        except OSError:
            pass
        return base / "icons" / "champions"

    @property
    def icons_dir(self) -> Path:
        """Folder of the bundled champion icons."""
        return self._icons_dir

    def _load_index(self) -> None:
        index_path = self._icons_dir / "index.json"
        raw_list: list[Any] = []
        try:
            with open(index_path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            if isinstance(data, dict):
                self.patch = str(data.get("patch") or "")
                raw_list = data.get("champions") or []
            elif isinstance(data, list):
                raw_list = data
        except FileNotFoundError:
            log.warning("Champion index not found: %s", index_path)
        except Exception:
            log.exception("Cannot read champion index %s", index_path)
        entries: list[ChampionEntry] = []
        for item in raw_list if isinstance(raw_list, list) else []:
            entry = self._entry_from_json(item)
            if entry is not None:
                entries.append(entry)
        if not entries:
            entries = self._entries_from_png_files()
        if self._runtime_data:
            entries += self._runtime_entries({e.alias.casefold() for e in entries})
        self._set_entries(entries)

    def _runtime_entries(self, known: set[str]) -> list[ChampionEntry]:
        """Champions of the runtime Data Dragon data missing from the bundled index (new releases)."""
        out: list[ChampionEntry] = []
        try:
            from treeaicoach import game_data

            for item in game_data.champions_data().get("champions") or []:
                entry = self._entry_from_json(item)
                if entry is not None and entry.alias.casefold() not in known:
                    out.append(entry)
                    known.add(entry.alias.casefold())
            if out:
                log.info("Champions added from the Data Dragon refresh: %s", ", ".join(e.alias for e in out))
        except Exception:
            log.debug("Runtime champion data unavailable", exc_info=True)
        return out

    def reload_index(self) -> None:
        """Re-read the index (+ runtime data); called after a Data Dragon update. Never raises."""
        try:
            self._load_index()
        except Exception:
            log.exception("ChampionDB.reload_index failed")

    @staticmethod
    def _entry_from_json(item: Any) -> ChampionEntry | None:
        if not isinstance(item, dict):
            return None
        alias = alias_from_raw(str(item.get("alias") or "")).strip()
        if not alias or not normalize_name(alias):
            return None
        tags = item.get("tags") or ()
        return ChampionEntry(
            alias=alias,
            key=_safe_int(item.get("key"), 0),
            name_en=str(item.get("name_en") or alias),
            name_fr=str(item.get("name_fr") or item.get("name_en") or alias),
            icon_file=str(item.get("icon") or f"{alias}.png"),
            tags=tuple(str(t) for t in tags) if isinstance(tags, (list, tuple)) else (),
        )

    def _entries_from_png_files(self) -> list[ChampionEntry]:
        """Fallback when index.json is missing: one entry per bundled PNG."""
        out: list[ChampionEntry] = []
        try:
            for p in sorted(self._icons_dir.glob("*.png")):
                out.append(ChampionEntry(p.stem, 0, p.stem, p.stem, p.name))
        except OSError:
            pass
        if out:
            log.warning("Champion index missing: %d entries built from icon files", len(out))
        return out

    def _set_entries(self, entries: list[ChampionEntry]) -> None:
        by_norm: dict[str, ChampionEntry] = {}
        by_key: dict[int, ChampionEntry] = {}
        # aliases first so that a localized name can never shadow another champion's alias
        for e in entries:
            by_norm.setdefault(normalize_name(e.alias), e)
            if e.key:
                by_key.setdefault(e.key, e)
        for e in entries:
            for name in (e.name_en, e.name_fr):
                k = normalize_name(name)
                if k:
                    by_norm.setdefault(k, e)
        with self._lock:
            self._entries = sorted(entries, key=lambda e: e.alias.lower())
            self._by_norm = by_norm
            self._by_key = by_key
            self._lru.clear()

    # ------------------------------------------------------------------ lookup
    def get(self, alias_or_raw: str) -> ChampionEntry | None:
        """Entry for an alias, raw name, localized name (EN/FR) or numeric key; case-insensitive."""
        if alias_or_raw is None:
            return None
        try:
            if isinstance(alias_or_raw, bool):
                return None
            if isinstance(alias_or_raw, (int, np.integer)):
                return self._by_key.get(int(alias_or_raw))
            if not isinstance(alias_or_raw, str):
                return None
            s = alias_from_raw(alias_or_raw)
            if s.isdigit():
                return self._by_key.get(int(s))
            k = normalize_name(s)
            return self._by_norm.get(k) if k else None
        except Exception:
            log.debug("ChampionDB.get(%r) failed", alias_or_raw, exc_info=True)
            return None

    def by_key(self, key: int) -> ChampionEntry | None:
        """Entry for a numeric champion id."""
        return self._by_key.get(_safe_int(key, -1))

    def canonical_alias(self, alias_or_name: str) -> str:
        """Alias spelled as in the index (``"monkeyking"`` -> ``"MonkeyKing"``), else cleaned input."""
        entry = self.get(alias_or_name)
        return entry.alias if entry is not None else alias_from_raw(alias_or_name)

    def all(self) -> list[ChampionEntry]:
        """All champions, sorted by alias."""
        return list(self._entries)

    def __len__(self) -> int:
        return len(self._entries)

    def __contains__(self, alias: object) -> bool:
        return isinstance(alias, str) and self.get(alias) is not None

    # ------------------------------------------------------------------ icons
    @property
    def cache_dir(self) -> Path | None:
        """Folder of downloaded skin icons (default: ``paths.cache_dir()``, resolved lazily)."""
        with self._lock:
            if not self._cache_dir_resolved:
                self._cache_dir_resolved = True
                try:
                    self._cache_dir = _default_cache_dir()
                except Exception:
                    log.debug("No cache dir", exc_info=True)
                    self._cache_dir = None
            return self._cache_dir

    def cached_icon_path(self, alias: str, skin_id: int) -> Path | None:
        """Path where the icon of ``alias`` / ``skin_id`` is (or would be) cached."""
        entry = self.get(alias)
        cdir = self.cache_dir
        if entry is None or cdir is None:
            return None
        return cdir / f"{entry.alias}_{max(0, _safe_int(skin_id, 0))}.png"

    def load_icon(self, alias: str, skin_id: int = 0) -> np.ndarray | None:
        """Round champion portrait (RGBA uint8, a fresh copy), skin icon if cached, else base icon.

        Returns ``None`` for an unknown champion or if no image can be read. Never raises.
        """
        try:
            entry = self.get(alias)
            if entry is None:
                return None
            skin = max(0, _safe_int(skin_id, 0))
            key = (entry.alias, skin)
            with self._lock:
                img = self._lru.get(key)
                if img is not None:
                    self._lru.move_to_end(key)
                    return img.copy()
            img = None
            cdir = self.cache_dir
            if cdir is not None:
                img = read_rgba(cdir / f"{entry.alias}_{skin}.png")
            if img is None:
                img = read_rgba(self._icons_dir / entry.icon_file)
            if img is None and cdir is not None and skin != 0:
                img = read_rgba(cdir / f"{entry.alias}_0.png")    # new champion: downloaded base icon
            if img is None:
                if entry.alias not in self._warned_missing_icon:
                    self._warned_missing_icon.add(entry.alias)
                    log.warning("No icon found for champion %s", entry.alias)
                return None
            img.setflags(write=False)
            with self._lock:
                self._lru[key] = img
                self._lru.move_to_end(key)
                while len(self._lru) > ICON_LRU_SIZE:
                    self._lru.popitem(last=False)
            return img.copy()
        except Exception:
            log.exception("load_icon(%r, %r) failed", alias, skin_id)
            return None

    def clear_icon_cache(self) -> None:
        """Forget the in-memory icons (files are kept)."""
        with self._lock:
            self._lru.clear()

    # ------------------------------------------------------------------ skin downloads
    def prefetch_skin_icons(self, players: Iterable["PlayerInfo"] | None, allow_network: bool = True) -> None:
        """Download missing skin icons of ``players`` in a background daemon thread.

        Idempotent (already cached / queued / 404 skins are skipped), returns immediately,
        no-op when ``allow_network`` is false. Never raises.
        """
        if not allow_network:
            return
        try:
            jobs: list[tuple[str, int]] = []
            for p in list(players or []):
                if isinstance(p, dict):
                    alias = p.get("champion_alias") or p.get("alias")
                    skin = p.get("skin_id", 0)
                else:
                    alias = getattr(p, "champion_alias", None)
                    skin = getattr(p, "skin_id", 0)
                entry = self.get(alias) if alias else None
                skin_n = _safe_int(skin, 0)
                if entry is None:
                    continue
                if skin_n <= 0 or not self._has_bundled_icon(entry):
                    if not self._has_bundled_icon(entry):
                        jobs.append((entry.alias, 0))      # champion newer than the build: base icon
                    if skin_n <= 0:
                        continue
                jobs.append((entry.alias, skin_n))
            if not jobs:
                return
            cdir = self.cache_dir
            if cdir is None:
                return
            now = time.monotonic()
            with self._lock:
                for key in jobs:
                    if key in self._queued or key in self._missing or key in self._downloaded:
                        continue
                    failed = self._failed_at.get(key)
                    if failed is not None and now - failed < RETRY_AFTER_S:
                        continue
                    if (cdir / f"{key[0]}_{key[1]}.png").is_file():
                        self._downloaded.add(key)
                        continue
                    self._queue.append(key)
                    self._queued.add(key)
                if self._queue and (self._worker is None or not self._worker.is_alive()):
                    self._stop.clear()
                    self._worker = threading.Thread(target=self._download_loop,
                                                    name="skin-icon-prefetch", daemon=True)
                    self._worker.start()
        except Exception:
            log.exception("prefetch_skin_icons failed")

    def wait_for_prefetch(self, timeout: float = 10.0) -> bool:
        """Block until the download thread is idle (tests / shutdown). True if idle."""
        deadline = time.monotonic() + max(0.0, float(timeout))
        while True:
            with self._lock:
                worker = self._worker
            if worker is None or not worker.is_alive():
                return True
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                return False
            worker.join(min(remaining, 0.1))

    def close(self) -> None:
        """Ask the download thread to stop after the current request."""
        self._stop.set()
        with self._lock:
            self._queue.clear()
            self._queued.clear()

    def _download_loop(self) -> None:
        while not self._stop.is_set():
            with self._lock:
                if not self._queue:
                    self._worker = None
                    return
                key = self._queue.popleft()
            try:
                if time.monotonic() < self._offline_until:
                    with self._lock:
                        self._failed_at[key] = time.monotonic()
                else:
                    self._download_one(key)
            except Exception:
                log.exception("Skin icon download crashed for %s", key)
                with self._lock:
                    self._failed_at[key] = time.monotonic()
            finally:
                with self._lock:
                    self._queued.discard(key)
        with self._lock:
            if self._worker is threading.current_thread():
                self._worker = None

    def _has_bundled_icon(self, entry: ChampionEntry) -> bool:
        try:
            return (self._icons_dir / entry.icon_file).is_file()
        except OSError:
            return False

    def base_icon_url(self, alias: str) -> str:
        """CommunityDragon URL of a champion's base minimap circle icon."""
        base = (self.base_url or CDRAGON_CHARACTERS_URL).rstrip("/")
        return BASE_ICON_URL_TEMPLATE.format(base=base, alias=urllib.parse.quote(alias.lower()))

    def skin_icon_url(self, alias: str, skin_id: int) -> str:
        """CommunityDragon URL of a skin's minimap circle icon."""
        base = (self.base_url or CDRAGON_CHARACTERS_URL).rstrip("/")
        a = urllib.parse.quote(alias.lower())
        return SKIN_ICON_URL_TEMPLATE.format(base=base, alias=a, skin=int(skin_id))

    def _download_one(self, key: tuple[str, int]) -> None:
        alias, skin = key
        cdir = self.cache_dir
        if cdir is None:
            return
        dest = cdir / f"{alias}_{skin}.png"
        if dest.is_file():
            with self._lock:
                self._downloaded.add(key)
            return
        urls = [self.skin_icon_url(alias, skin)]
        if skin == 0:                                # base icon of a champion newer than the build
            urls.insert(0, self.base_icon_url(alias))
        data = b""
        url = urls[-1]
        for i, url in enumerate(urls):
            try:
                data = self._fetch(url)
                break
            except urllib.error.HTTPError as exc:
                try:
                    exc.close()
                except Exception:
                    pass
                if exc.code in (403, 404, 410) and i < len(urls) - 1:
                    continue                         # try the other file name
                with self._lock:
                    if exc.code in (403, 404, 410):
                        self._missing.add(key)
                    else:
                        self._failed_at[key] = time.monotonic()
                log.debug("Skin icon %s: HTTP %s", url, exc.code)
                return
            except Exception as exc:  # URLError, timeout, OSError, http.client errors...
                with self._lock:
                    self._failed_at[key] = time.monotonic()
                    self._offline_until = time.monotonic() + RETRY_AFTER_S
                log.info("Skin icon download unavailable (%s): %s", url, exc)
                return
        if len(data) > MAX_DOWNLOAD_BYTES:
            with self._lock:
                self._missing.add(key)
            log.debug("Skin icon %s too large", url)
            return
        img = decode_rgba(data)
        if img is None:
            with self._lock:
                self._missing.add(key)
            log.debug("Skin icon %s is not a valid image", url)
            return
        if img.shape[:2] != (CACHED_ICON_SIZE, CACHED_ICON_SIZE):
            img = cv2.resize(img, (CACHED_ICON_SIZE, CACHED_ICON_SIZE), interpolation=cv2.INTER_AREA)
        ok, buf = cv2.imencode(".png", cv2.cvtColor(img, cv2.COLOR_RGBA2BGRA))
        if not ok:
            return
        if not self._atomic_write(dest, buf.tobytes()):
            with self._lock:
                self._failed_at[key] = time.monotonic()
            return
        with self._lock:
            self._downloaded.add(key)
            self._lru.pop(key, None)
        log.info("Skin icon cached: %s skin %d", alias, skin)

    def _fetch(self, url: str) -> bytes:
        """GET ``url`` (no proxy for loopback test servers); raises urllib errors."""
        host = (urllib.parse.urlsplit(url).hostname or "").lower()
        opener = _no_proxy_opener() if host in _LOOPBACK else urllib.request.build_opener()
        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "image/png,*/*"})
        with opener.open(req, timeout=DOWNLOAD_TIMEOUT_S) as resp:
            return resp.read(MAX_DOWNLOAD_BYTES + 1)

    @staticmethod
    def _atomic_write(dest: Path, data: bytes) -> bool:
        tmp_name = None
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            fd, tmp_name = tempfile.mkstemp(prefix=f".{dest.stem}-", suffix=".tmp", dir=str(dest.parent))
            with os.fdopen(fd, "wb") as fh:
                fh.write(data)
                fh.flush()
                try:
                    os.fsync(fh.fileno())
                except OSError:
                    pass
            os.replace(tmp_name, dest)
            tmp_name = None
            return True
        except Exception:
            log.warning("Cannot write skin icon %s", dest, exc_info=True)
            return False
        finally:
            if tmp_name is not None:
                try:
                    os.unlink(tmp_name)
                except OSError:
                    pass


# ---------------------------------------------------------------------- shared instance
_default_db: ChampionDB | None = None
_default_db_lock = threading.Lock()


def get_default_db() -> ChampionDB:
    """Process-wide :class:`ChampionDB` on the bundled assets (created lazily, thread-safe)."""
    global _default_db
    db = _default_db
    if db is not None:
        return db
    with _default_db_lock:
        if _default_db is None:
            _default_db = ChampionDB()
            try:  # new champions / names after a runtime Data Dragon update
                from treeaicoach import game_data

                game_data.add_listener(_default_db.reload_index)
            except Exception:
                log.debug("game_data listener not registered", exc_info=True)
        return _default_db
